version: "3.9"
services:
	exadeldevops: # My image
        image: exadeldevops/docker
        ports:
            - "8080:8080"
        volumes: 
    java: # Java image
        container_name: exadeljava
        image: openjdk:8
        volumes:
        - ./:/app
        working_dir: /app
        ports:
            - 8080:8080
        depends_on: # Starts after starting mysql database
            - mysql_db
            links:
            - mysql_db:app_db
        mysql_db:
            image: "mysql:8.0"
            restart: always
            ports:
                - 3306:3306
            environment:
                MYSQL_DATABASE: java_to_dev_app_db
                MYSQL_USER: java_to_dev
                MYSQL_PASSWORD: mysqlpasswd
                MYSQL_ROOT_PASSWORD: mysqlrootpasswd 
